export const productsData = [
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/chair.png",
    category: "Chair",
    name: "White Aesthetic Chair",
    desc: "Combination of wood and wool",
    price: 63.47,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
  {
    image: "/pages/index/lamp.png",
    category: "Lamp",
    name: "Bardono Smart Lamp",
    desc: "Easy to use with bluetooth connection",
    price: 62.23,
  },
  {
    image: "/pages/index/sofa.png",
    category: "Sofa",
    name: "Sofa Empuk Banget",
    desc: "Using kapuk randu material",
    price: 58.39,
  },
  {
    image: "/pages/index/bookshelf.png",
    category: "Living Room",
    name: "Wooden Bookshelf",
    desc: "Combination of wood and wool",
    price: 58.39,
  },
];
